# .github/workflows/deploy.yml
name: Build and Deploy Go API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: go build -o main .

      - name: Run Tests (optional)
        run: go test ./...

      - name: Docker Build
        run: |
          docker build -t go-api .

      # Add push to Docker Hub/GHCR or deployment step here if needed
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.WRITEPAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/caseymal/go-api
          docker tag go-api $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
