# .github/workflows/deploy.yml
name: Build and Deploy Go API to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry with PAT
      run: echo "${{ secrets.WRITEPAT }}" | docker login ghcr.io -u caseymal --password-stdin

    - name: Build and Push Docker Image with Commit SHA
      run: |
        IMAGE_NAME=ghcr.io/caseymal/go-api
        IMAGE_TAG=${GITHUB_SHA}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig

    - name: Update Kubernetes Deployment with New Image
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
        IMAGE_NAME=ghcr.io/caseymal/go-api:${GITHUB_SHA}
        kubectl set image deployment/go-api go-api=$IMAGE_NAME -n default
