# .github/workflows/deploy.yml
name: Build and Deploy Go API to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry with PAT
      run: echo "${{ secrets.WRITEPAT }}" | docker login ghcr.io -u caseymal --password-stdin

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u caseymal --password-stdin

    - name: Build and Push Docker Image to Docker Hub
      run: |
        IMAGE_NAME=caseymal/go-api
        IMAGE_TAG=${GITHUB_SHA}
        echo "Commit SHA is $GITHUB_SHA"
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
